on: [push]

jobs:
  chain_bench_scan:
    runs-on: ubuntu-latest
    name: Test Job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Chain Bench
        id: oss-chain-bench
        uses: ./
        with:
          repository-url: ${{ github.server_url }}/${{ github.repository }}
          github-token: ${{secrets.GITHUB_TOKEN }}
          scm-platform: "github"

      - name: Echo
        run: echo ${{ steps.oss-chain-bench.outputs.oss-chain-bench-result }}
